name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set ssh key
        run: |
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
      - name: Deploy
        run: ssh -o StrictHostKeyChecking=no ubuntu@35.158.106.188 "cd laravel && git pull origin master"
      
      - name: Setup aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: test where am i
        run: pwd && ls -la
      # - name: Deploy assets to s3
      #   run: aws s3 sync ./laravel/public s3://laravel-assets-with-s3 --delete