name: Deploy
description:  Deploy to AWS EC2

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set ssh key
        run: |
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@35.158.106.188 "whoami"